#install.packages(c("devtools","BiocManager"))
#BiocManager::install("VariantAnnotation")
#devtools::install_github("inzilico/imputeqc", build_vignettes = TRUE)
library(imputeqc)
# The original file is true dataset, the masks file was generated by mask_imputeqc.R, and the imputed file is test dataset
EstimateQuality((origin="chromosome1_selected_site_biallelic.vcf.gz",masks="masks.RDS",imputed="chromosome1_masked10.vcf.gz.m1.imputed.vcf.gz")
